apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "websight-ce.fullname" . }}-cms
  labels:
    app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
    app.kubernetes.io/instance: {{ .Release.Name }}-cms
    app.kubernetes.io/version: {{ .Values.cms.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: cms
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
      app.kubernetes.io/instance: {{ .Release.Name }}-cms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
        app.kubernetes.io/instance: {{ .Release.Name }}-cms
    spec:
      containers:
        - env:
            - name: LEASE_CHECK_MODE
              value: LENIENT
            - name: MONGODB_HOST
              value: {{ include "websight-ce.fullname" . }}-mongo
            - name: MONGODB_PORT
              value: "27017"
            - name: WS_ADMIN_PASSWORD
              value: wsadmin
            - name: WS_ADMIN_USERNAME
              value: wsadmin
          image: "{{ .Values.cms.image.repository }}:{{ .Values.cms.image.tag }}"
          name: cms
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.cms.resources.requests.memory }}
              cpu: {{ .Values.cms.resources.requests.cpu }}
            limits:
              memory: {{ .Values.cms.resources.limits.memory }}
              cpu: {{ .Values.cms.resources.limits.cpu }}
          volumeMounts:
            - mountPath: /websight/logs
              name: cms-logs
            - mountPath: /websight/docroot
              name: site-repository
          {{- if .Values.cms.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.cms.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.cms.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.cms.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.cms.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.cms.livenessProbe.successThreshold }}
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
          {{- end }}
          {{- if .Values.cms.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.cms.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.cms.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.cms.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.cms.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.cms.readinessProbe.successThreshold }}
            httpGet:
              path: /apps/websight-authentication/login.html
              port: 8080
              scheme: HTTP
          {{- end }}
      restartPolicy: Always
      volumes:
        - name: cms-logs
          persistentVolumeClaim:
            claimName: {{ include "websight-ce.fullname" . }}-cms-logs
        - name: site-repository
          persistentVolumeClaim:
            claimName: {{ include "websight-ce.fullname" . }}-site-repository
status: {}
